apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  labels:
    codefresh.io/product: rollout
    env: dev
spec:
  project: default
  source:
    repoURL: https://github.com/kim-codefresh/rollout-test-git-source.git
    targetRevision: main
    path: rollout-apps/dev
  destination:
    name: in-cluster
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
