apiVersion: v1
kind: Service
metadata:
  name: canary-demo
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
      readinessProbe:
        httpGet:
          path: /nonExist # test degraded
          port: 80
      
  selector:
    app: canary-demo
  type: LoadBalancer
